apiVersion: batch/v1
kind: Job
metadata:
  name: fake-orders-publisher
  namespace: keda
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: publisher
          image: nkalapala24/fake-orders-publisher:latest
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
          args: ["--count", "500"]
